//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const genTemplate = `// Code generated by scripts/gen_licenses.go. DO NOT EDIT.

package licenses

type LicenseEntry struct {
	LibraryName string
	Content     string
}

var ProjectLicense = {{ .ProjectLicense }}

var ThirdPartyLicenses = []LicenseEntry{
{{- range .ThirdParty }}
	{
		LibraryName: "{{ .LibraryName }}",
		Content: {{ .Content }},
	},
{{- end }}
}
`

type TemplateData struct {
	ProjectLicense string
	ThirdParty     []LicenseData
}

type LicenseData struct {
	LibraryName string
	Content     string
}

func main() {
	fmt.Println("Running go-licenses...")
	
	tempDir := "temp_licenses_gen"
	_ = os.RemoveAll(tempDir)
	
	cmd := exec.Command("go", "run", "github.com/google/go-licenses@latest", "save", "./...", "--save_path="+tempDir)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Printf("go-licenses failed: %v\n", err)
		os.Exit(1)
	}
	defer os.RemoveAll(tempDir)

	var entries []LicenseData

	err := filepath.WalkDir(tempDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			relPath, _ := filepath.Rel(tempDir, path)
			dirPath := filepath.Dir(relPath)
			dirPath = strings.ReplaceAll(dirPath, "\\", "/")
			
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			
			// Filter out the project itself since we handle it separately at index 0
			if dirPath == "github.com/yinfall/gdup" {
				return nil
			}

			// Quote the content properly for Go string literal
			quotedContent := fmt.Sprintf("%#v", string(content))
			
			entries = append(entries, LicenseData{
				LibraryName: dirPath,
				Content:     quotedContent,
			})
		}
		return nil
	})

	if err != nil {
		fmt.Printf("Error walking licenses: %v\n", err)
		os.Exit(1)
	}

	tmpl, err := template.New("gen").Parse(genTemplate)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Read project's own license
	projectLicenseBytes, err := os.ReadFile("LICENSE")
	var projectLicenseContent string
	if err == nil {
		projectLicenseContent = fmt.Sprintf("%#v", string(projectLicenseBytes))
	} else {
		projectLicenseContent = `""`
	}

	tmplData := TemplateData{
		ProjectLicense: projectLicenseContent,
		ThirdParty:     entries,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, tmplData); err != nil {
		fmt.Printf("Error executing template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting source: %v\n", err)
		// Write unformatted for debugging
		os.WriteFile("internal/licenses/data_gen.go", buf.Bytes(), 0644)
		os.Exit(1)
	}

	err = os.WriteFile("internal/licenses/data_gen.go", formatted, 0644)
	if err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated internal/licenses/data_gen.go")
}
